### ISSUE TITLE
关于训练数据的咨询

### ISSUE THREAD

**Issue by rain2050** [Mesks/FPNforV-PCC#1]
感谢您开源了优秀的工作，但是目前没有在网络上查找到您的论文，是还在投稿过程中吗？同时您可以提供一下训练的数据集吗，或者是数据集是如何制作的呢？期待您的回复，十分感谢。

**Comment by Mesks** [comment]
您好，非常感谢您的认可。

论文正在审稿中，神经网络的训练数据集可能无法公开（因为太大了），也没必要公开，因为代码中已包括了数据提取程序，即dataExtracting文件夹下的程序。

如果问的是点云测试序列如何获取的话，可以参考readme中Resource Link下列出MPEG test sequence的两个网址，其一是MPEG官网提供的程序，但目前似乎只有Owlii的常用点云测试序列是动态点云（basketball_player and dancer），8iVSLF的点云目前官方只提4080*4080*4080分辨率的超大动态点云测试序列（Thaidancer），1280*1280*1280的Longdress、Soldier、Queen、Boxer、Redandblack、Loot官方不再提供，如果有必要的话可以尝试去第二个网址下载，但链接似乎不太稳定。

希望我的回答对您有帮助。



在 2023-12-18 11:29:16，"小白拜学习" ***@***.***> 写道：

感谢您开源了优秀的工作，但是目前没有在网络上查找到您的论文，是还在投稿过程中吗？同时您可以提供一下训练的数据集吗，或者是数据集是如何制作的呢？期待您的回复，十分感谢。

**Comment by rain2050** [comment]
十分感谢您的回复，我看您另一篇发表在C&G的优秀工作中描述“当我们构建LFCN训练的数据集时，仅使用动态点云视频篮球运动员的8帧（第555-562帧）。”那您当前这个工作的训练集是用Owlii数据集构建的，还是用8iVSLF数据集构建的，每个模型取多少帧进行构建。期待您的回复，祝您科研顺利。

**Comment by Mesks** [comment]
同样是用Owlii数据集构建的，因为考虑到测试需要反映泛化能力，因此训练过程中没有使用任何8iVSLF的数据，而在仿真测试中全部使用8iVSLF的点云序列。在FPNforVPCC的工作中训练数据提取使用了16帧，并且如果您想进行类似的工作我强烈建议数据集越大越好，我分别测试了使用4、8、16帧提取数据来训练神经网络，最终的拟合效果一种比一种更好，受限于我的硬件设备最终没有使用更大的数据集。并且为了解决张量过大GPU显存不够的问题我采用每个epoch分步取张量训练的方法（当然如果能从硬件层面解决这个问题更好）。另外可能需要单独说明的是，FPN的输入张量维度是N×3×64×64。

**Comment by Mesks** [comment]
> 十分感谢您的回复，我看您另一篇发表在C&G的优秀工作中描述“当我们构建LFCN训练的数据集时，仅使用动态点云视频篮球运动员的8帧（第555-562帧）。”那您当前这个工作的训练集是用Owlii数据集构建的，还是用8iVSLF数据集构建的，每个模型取多少帧进行构建。期待您的回复，祝您科研顺利。

同样是用Owlii数据集的basketball_player构建的，因为考虑到测试需要反映泛化能力，因此训练过程中没有使用任何8iVSLF的数据，而在仿真测试中全部使用8iVSLF的点云序列。在FPNforVPCC的工作中训练数据提取使用了32帧，并且如果您想进行类似的工作我强烈建议数据集越大越好，我分别测试了使用8、16、24、32帧提取数据来训练神经网络，最终的拟合效果一种比一种更好，受限于我的硬件设备最终没有使用更大的数据集。并且为了解决张量过大GPU显存不够的问题我采用每个epoch分步取张量训练的方法（当然如果能从硬件层面解决这个问题更好）。另外可能需要单独说明的是，FPN的输入张量维度是N×3×64×64。

**Comment by rain2050** [comment]
非常感谢您详细的解答，十分感谢，我先努力复现您的工作。同时期待您的论文早日accept。祝您科研顺利。

**Comment by Mesks** [comment]
> 非常感谢您详细的解答，十分感谢，我先努力复现您的工作。同时期待您的论文早日accept。祝您科研顺利。

不客气，也祝您科研顺利。

**Comment by Mesks** [comment]
> 非常感谢您详细的解答，十分感谢，我先努力复现您的工作。同时期待您的论文早日accept。祝您科研顺利。

想起之前在IEEE DataPort上曾公开过所提取的数据集，已更新相应的readme描述，如果需要与作者工作一致的数据集可以去那边下载。

**Comment by rain2050** [comment]
非常感谢您的帮助，我点进去看了，需要IEEE会员才能下载，然而我并不是，十分感谢您的帮助。
